<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-24T14:04:04Z" name="Suite" finished-at="2025-07-24T14:04:14Z" duration-ms="9858">
    <groups>
      <group name="smoke">
        <method signature="RegisterTest.validationRegistrationLink()[pri:0, instance:testClasses.RegisterTest@2ed0fbae]" name="validationRegistrationLink" class="testClasses.RegisterTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-07-24T14:04:04Z" name="Test" finished-at="2025-07-24T14:04:14Z" duration-ms="9858">
      <class name="testClasses.RegisterTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testClasses.RegisterTest@2ed0fbae]" started-at="2025-07-24T14:04:04Z" name="setUp" finished-at="2025-07-24T14:04:13Z" duration-ms="9406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validationRegistrationLink()[pri:0, instance:testClasses.RegisterTest@2ed0fbae]" started-at="2025-07-24T14:04:13Z" name="validationRegistrationLink" finished-at="2025-07-24T14:04:13Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testClasses.RegisterTest.validationRegistrationLink(RegisterTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationRegistrationLink -->
      </class> <!-- testClasses.RegisterTest -->
      <class name="testClasses.LoginTest">
        <test-method signature="executeLoginTest()[pri:0, instance:testClasses.LoginTest@25a65b77]" started-at="2025-07-24T14:04:04Z" name="executeLoginTest" finished-at="2025-07-24T14:04:04Z" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executeLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.LoginTest@25a65b77]" started-at="2025-07-24T14:04:14Z" name="tearDown" finished-at="2025-07-24T14:04:14Z" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.RegisterTest@2ed0fbae]" started-at="2025-07-24T14:04:14Z" name="tearDown" finished-at="2025-07-24T14:04:19Z" duration-ms="5066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
